### ISSUE TITLE
Any plan to migrate to powershell?

### ISSUE THREAD

**Issue by welpdx** [bmrf/tron#219] opened 2023-08-01 07:48 UTC
With PowerShell becoming the new norm for windows, will tron consider migrating over to powershell?

**Comment by princessmortix** [comment] 2023-08-15 23:43
Possible duplicate of #216.

**Comment by vocatus** [comment] 2023-08-23 17:36
[Not currently.](https://www.reddit.com/r/TronScript/wiki/index#wiki_why_is_tron_written_in_batch.3F_why_not_powershell.3F)

**Closed** 2023-08-23 17:37 UTC
