### ISSUE TITLE
boot problems after -asm tag

### ISSUE THREAD

**Issue by orrinwitt** [bmrf/tron#169] opened 2019-09-11 17:20 UTC
So... I probably will not be able to provide enough information to be helpful here, since this issue was on a customer's computer and I won't be able to replicate it for testing. 
That said, I was working on a computer that was experiencing high disk usage to the point it was almost unusable. For this reason, I thought maybe I should run Tron in safe mode this time, to circumvent whatever was causing it. 
But when I ran the script with the -asm tag, I ran into all kinds of problems even being able to boot into windows at all. Something happened to the boot record or something. I was eventually able to fix it with some command prompt stuff like bootrec /rebuildbcd, etc., but it was quite a circus. When I finally got back into Windows, I thought whatever caused the problem was probably fixed now, and maybe had nothing to do with the Tron script. But when I ran it again (with the -asm tag still), the issue returned, a little worse. 
Got back in after jumping through more command prompt hoops, and Tron is currently doing its thing in normal mode. I'm not about to try to replicate the issue, but thought I should pass it along in case it is something fixable within the script. I know safe mode is not necessary, and not even recommended for most cases anymore, but it should still work when needed.
Any ideas? or have you seen this behavior before?

**Comment by vocatus** [comment] 2019-09-17 13:20
Hi @orrinwitt , thanks for the report. I haven't seen this before when using `-asm`, but every so often you get weird one-off issues. When you run with `-asm` Tron just sets the flag to start in Safe Mode, then triggers a reboot. 

You can see the two commands Tron executes [here](https://github.com/bmrf/tron/blob/d9955aed0e3760dc8c612b808e7868ebf5a7fbac/tron.bat#L382-L385). You can test those manually on the system and see if it recreates the issue.

**Comment by BennyAlex** [comment] 2019-09-27 17:24
a high disk usage can also mean, that the disk ist damaged/getting broken soon so maybe it was to much after the restart

**Comment by vocatus** [comment] 2019-10-09 00:00
Hi @BennyAlex , since I can't reproduce this on my end I'm closing the issue. Please let me know if you experience this again.

**Closed by vocatus** 2019-10-09 00:00 UTC
