### ISSUE TITLE
[Request] Integrate SDI - Snappy Driver installer  

### ISSUE THREAD

**Issue by d0t1q** [bmrf/tron#141] opened 2018-06-20 16:24 UTC
I've had a pretty good experience with SDI and it seems like this might be a good feature to implement at the end of the cleaning process  

https://sdi-tool.org/

SDI also provides a few CLI options - http://snappy-driver-installer.sourceforge.net/en/usage.php

**Comment by kronflux** [comment] 2018-06-21 02:46
This is a TERRIBLE idea. While driver updaters may "seem" like a good idea, easy to use and all that - they cause more trouble than they're worth.
Despite two devices sharing identical USB controllers and various components, quite often there are minor differences which certain motherboard vendors have to support with changes to the manufacturer generic drivers.

Best practices are to use ONLY the drivers provided by your motherboard/PC manufacturer, as they are certified for use with your particular device and have been thoroughly tested.

In fact, I even typically recommend that people disable the Microsoft built-in device driver downloading functionality from Windows Update, as often the drivers end up breaking things, rather than functioning as expected.

There are MANY driver updaters out there, but if you choose to use them, you're going against the recommendations of the device manufacturer(and believe it or not, in some cases voiding your warranty) as well as the recommendations of the IT community in general.

**Comment by kronflux** [comment] 2018-06-21 02:48
also, "newer" isn't always "better", especially in the field of communication with devices.

**Comment by madbomb122** [comment] 2018-06-21 15:18
I totally agree with Kronflux, also it would increase the size of Tron too much if the drivers file are included. Tron is supposed to be light-weight.

Only time you should use a program like that is if you cant get the manufacturer's drivers or there is none supplied by the manufacturer for your current OS.

Also no reasons to update drivers unless you are having problems with your current ones or you are required/need to update them.

**Comment by d0t1q** [comment] 2018-06-21 15:19
You might want to check on the crc of a few of the drivers before commenting as they are grabbed from a repository of manufacture drivers, its not downloading unsigned custom drivers none of this would void warranty as you say. The only real valid comment you've made is newer isn't always better and really that's just up to personal preference. I know I've seen posts in the subreddit complaining that tron has removed bloatware drivers before(remove the bloatware software which took the driver with it),  this would just help alleviate that pain.

@madbomb122 this downloads drivers as needed, would only increase the size by a few mbs.

**Comment by madbomb122** [comment] 2018-06-21 15:57
@d0t1q Yes i know it downloads drivers as needed, but it downloads the driver packs (not the driver itself) which can be from 7mb to 2.5gb (per pack), and yes i see what you are suggesting, is to have the program run after the cleaning process.

**Comment by kronflux** [comment] 2018-06-23 01:31
@d0t1q As someone who's been in IT, and has worked extensively with device drivers and Windows, I can tell you I've seen literally thousands of issues caused by these types of tools, and the drivers they provide.

You are correct in many instances, where the drivers are straight from the manufacturers. If you read my comment and understood it in full, you'd also understand that that's part of the problem - and the same reason why Microsoft Windows Update provided drivers also cause problems on many systems.
The reason is that the manufacturer drivers are not tailored to the hardware the devices are being deployed on.

The best example I can provide that can help you to understand(this is FAR from the only instance) is in the 2013-2015 range, laptop manufacturers made the decision to put dual graphics cards into their laptops. Intel dedicated graphics and nVidia dedicated graphics. The idea was to give better battery life without the sacrifice of graphics performance, where the system would use the intel dedicated graphics for lower graphics tasks, and use the nVidia for the tasks that demand more video performance.
The laptop manufacturers had to write custom versions of both the Intel drivers as well as the nVidia drivers, otherwise the functionality wouldn't work correctly.
If you installed the drivers straight from nVidia, you'd actually brick the functionality entirely.
The same went for using drivers straight from Intel.

There's no way for driver updaters to know what changes the PC/Laptop/Motherboard manufacturer makes to drivers to achieve the best stability and performance out of the components they use. Which is why it very often leads to more issues.

And no, it's got nothing to do with personal preference. The comment I made about "newer isn't always better" directly relates to experience. There have been MANY instances(unfortunately nVidia is a big focus for a lot of these) where updated drivers even straight from the manufacturer cause more issues than they offered benefits. The GeForce 8800 series was a great example of this. The first few drivers worked fine, but for something like 3 years the updated drivers released by nVidia caused the card to create all sorts of issues ranging from crashing games, to changing the game speed, to even causing visual artifacts.

Trust me when I say I've "looked into" the solution, it's far from a new concept, and they themselves are not a new contender to the battle.

Please take YOUR time to research how drivers work, and how chip manufacturers release drivers versus the way that PC manufacturers do.
Please also note that your tone is not appreciated, the comments being made here are to help the maintainer of the project, and are not directly intended for you, but the idea you presented itself.
Nothing is meant as an attack on you.

ANYone in IT who has any amount of personal experience will tell you exactly the same things as I have.

**Comment by vocatus** [comment] 2018-07-03 17:46
Just catching up with Tron work, chiming in and closing out the issue.

@d0t1q thanks for the suggestion, I actually often use SDI or SDI Origin myself, and have thought about adding it to Tron, but ultimately  decided not to for the following reasons (some mentioned by @kronflux and others):

1. Sometimes driver updates brick things, or break touchscreens, etc. It happens infrequently, but I've had it happen enough times that I prefer to leave driver updates as a manually-executed function based on the situation.

2. It's trivially easy to drop SDI in `\resources\stage_8_custom_scripts` on your copy of Tron and it will auto-execute the driver updates (just throw a `.bat` wrapper script in there).

Hope this helps, and thanks everyone for the comments.

**Closed by vocatus** 2018-07-03 17:46 UTC

**Comment by DeadlyDad** [comment] 2020-11-08 02:25
(I'm posting this just in case some folks are still using SDI from https://sdi-tool.org.)

The reason that SDI_**O**_ was created was that whoever took over the development of SDI actually inserted adware in it, so Glenn Delahoy created Snappy Driver Installer _Origin_ to give folks a clean version, which is still in constant development and can be found at https://www.snappy-driver-installer.org.

**Comment by vocatus** [comment] 2020-12-16 17:44
I personally love SDI/SDI Origin, but it would bloat the size of Tron by too much.

However, a good solution if you want to include it in Tron, is to put SDI in the Stage 8 folder, along with a script to run automatic driver update. The whole reason we implemented the stage 8 custom scripts portion of Tron was for situations exactly like this.
